### ISSUE TITLE
How use androidx libraries?

### ISSUE THREAD

**Issue by LinArcX** [HemanthJabalpuri/AndroidExplorer#3]
Hi. i want to use androidx libraries. like: androidx.appcompat, androidx.cardview,.. How integrate it into my project?

Edit: I've created a bare minimum application and tried to add support libraries to it:
https://github.com/MinimalAndroidDevelopment/madsw

It compiles without any issue, but in runtime i'll get [these errors](https://gist.github.com/LinArcX/ed3c34b2d3b11ae127c67f767dbc9403):

**Comment by LinArcX** [comment]
Fixed.

**Comment by iyxan23** [comment]
@LinArcX Can you tell how did you did it? I'm looking forward to use androidx libraries
