### ISSUE TITLE
Is apkbuilder necessary?

### ISSUE THREAD

**Issue by iyxan23** [HemanthJabalpuri/AndroidExplorer#4]
Hello, I'm currently messing around on how to build android apks manually, after reading your `build_new.sh` script, I installed some binaries as `aapt2`, `aapt`, `d8`, `java`, `zipaligner`, and `apksigner`, but I can't really seem to find `apkbuilder`. After some searching, I've found out that `apkbuilder` is deprecated. Is there like any other alternative or should I just continue using this `apkbuillder`?

Also, after some more searching, I also found this script that doesn't even need to use `apkbuilder`, is `apkbuilder` necessary?
https://github.com/WanghongLin/miscellaneous/blob/262491df620f835b4e3b9b1f0b0a7f89345e0229/tools/build-apk-manually.sh#L62

Thanks.

**Comment by HemanthJabalpuri** [comment]
@lyxan23

> Also, after some more searching, I also found this script that doesn't even need to use apkbuilder, is apkbuilder necessary?

It is not necessary. It can be used for other purposes but in this example it is not at all necessary. You can use the one you mentioned.

You can find apkbuilder that is compiled by me at 
[sdklib_25.3.0.jar](https://github.com/HemanthJabalpuri/AndroidExplorer/files/7930284/sdklib_25.3.0.jar.zip).
Just use `java -jar sdklib_25.3.0.jar.zip ...`

Thanks

**Comment by iyxan23** [comment]
Thanks for the fast response!
